[build]
  publish = "public"
  functions = "netlify/functions"

# URL amigável opcional: /api/data -> função data
[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200

[functions]
  node_bundler = "esbuild"
